"""
Standalone Strands Agent: returns_refunds_agent
Generated by AgentCore MCP Server

Integrations:
- Memory: Disabled
- Gateway: Disabled
- Knowledge Base: Enabled
"""

import os
import json
from strands import Agent, tool
from strands.models import BedrockModel
from strands_tools import retrieve
from strands_tools import current_time
from datetime import datetime

# Constants
MODEL_ID = "us.anthropic.claude-sonnet-4-5-20250929-v1:0"
REGION = "us-west-2"
SESSION_ID = "default-session"
ACTOR_ID = "default-actor"

# Model configuration
bedrock_model = BedrockModel(model_id=MODEL_ID, temperature=0.3)

# ============================================================================
# KNOWLEDGE BASE CONFIGURATION
# ============================================================================

# Load KB ID from config file
try:
    with open('kb_config.json', 'r') as f:
        kb_config = json.load(f)
        kb_id = kb_config.get('knowledge_base_id', 'YOUR_KB_ID_HERE')
except FileNotFoundError:
    kb_id = os.environ.get("KNOWLEDGE_BASE_ID", "YOUR_KB_ID_HERE")

print(f"✓ Knowledge Base ID: {kb_id}")

# System prompt
system_prompt = f"""You are a helpful returns and refunds assistant. Help customers check return eligibility, calculate refunds, and understand policies. Use the retrieve tool to access Amazon return policy documents for accurate information. Be friendly and accurate.

When using the retrieve tool, always pass these parameters:
- knowledgeBaseId: {kb_id}
- region: {REGION}
- text: the search query"""

# Custom tool definitions
@tool

def check_return_eligibility(purchase_date: str, category: str) -> str:
    """Check if an item can be returned based on purchase date and category.
    
    Args:
        purchase_date: Purchase date in YYYY-MM-DD format
        category: Product category (electronics, clothing, books, etc.)
    """
    try:
        purchase = datetime.strptime(purchase_date, '%Y-%m-%d')
        today = datetime.now()
        days_since_purchase = (today - purchase).days
        
        # Return windows by category
        return_windows = {
            'electronics': 30,
            'clothing': 60,
            'books': 30,
            'home': 90,
            'toys': 90,
            'default': 30
        }
        
        window = return_windows.get(category.lower(), return_windows['default'])
        
        if days_since_purchase <= window:
            return f"✓ Eligible for return. Item purchased {days_since_purchase} days ago. {category.title()} have a {window}-day return window. You have {window - days_since_purchase} days remaining."
        else:
            return f"✗ Not eligible for return. Item purchased {days_since_purchase} days ago, which exceeds the {window}-day return window for {category}."
    except ValueError:
        return "Error: Invalid date format. Please use YYYY-MM-DD format."

@tool
def calculate_refund_amount(price: float, condition: str, return_reason: str) -> str:
    """Calculate refund amount based on item price, condition, and return reason.
    
    Args:
        price: Original purchase price
        condition: Item condition (new, like-new, used, damaged)
        return_reason: Reason for return (defect, wrong-item, changed-mind, damaged-shipping)
    """
    refund_percentage = 1.0
    
    # Adjust based on condition
    condition_adjustments = {
        'new': 1.0,
        'like-new': 1.0,
        'used': 0.8,
        'damaged': 0.5
    }
    
    # Adjust based on reason
    reason_adjustments = {
        'defect': 1.0,
        'wrong-item': 1.0,
        'damaged-shipping': 1.0,
        'changed-mind': 0.9  # 10% restocking fee
    }
    
    condition_factor = condition_adjustments.get(condition.lower(), 0.8)
    reason_factor = reason_adjustments.get(return_reason.lower(), 0.9)
    
    refund_amount = price * condition_factor * reason_factor
    
    details = []
    if condition_factor < 1.0:
        details.append(f"Condition adjustment: {condition_factor * 100}%")
    if reason_factor < 1.0:
        details.append(f"Restocking fee: {(1 - reason_factor) * 100}%")
    
    result = f"Refund amount: ${refund_amount:.2f} (Original: ${price:.2f})"
    if details:
        result += "\n" + "\n".join(details)
    
    return result

@tool
def format_policy_response(policy_text: str, customer_situation: str = '') -> str:
    """Format policy information in a customer-friendly, easy-to-read way.
    
    Args:
        policy_text: The policy text to format
        customer_situation: Optional context about the customer's specific situation
    """
    formatted = "📋 Return Policy Summary\n" + "=" * 40 + "\n\n"
    
    if customer_situation:
        formatted += f"For your situation: {customer_situation}\n\n"
    
    # Clean up and format the policy text
    lines = policy_text.strip().split('\n')
    for line in lines:
        line = line.strip()
        if line:
            if line.isupper() or line.endswith(':'):
                formatted += f"\n{line}\n"
            else:
                formatted += f"• {line}\n"
    
    formatted += "\n" + "=" * 40
    formatted += "\n\n💡 Tip: If you have questions, I'm here to help clarify any part of this policy!"
    
    return formatted


def run_agent(user_input: str, session_id: str = SESSION_ID, actor_id: str = ACTOR_ID):
    """Run the agent with user input"""
    
    # Build tools list
    custom_tools = [retrieve, current_time, check_return_eligibility, calculate_refund_amount, format_policy_response]
    
    # Create agent
    agent = Agent(
        model=bedrock_model,
        tools=custom_tools,
        system_prompt=system_prompt
    )
    
    response = agent(user_input)
    return response.message["content"][0]["text"]

if __name__ == "__main__":
    # Example usage
    user_query = "Hello, how can you help me?"
    result = run_agent(user_query)
    print("\n" + "="*80)
    print("AGENT RESPONSE:")
    print("="*80)
    print(result)
