"""
Standalone Strands Agent: full_featured_returns_agent
Generated by AgentCore MCP Server

Integrations:
- Memory: Enabled
- Gateway: Enabled
- Knowledge Base: Enabled
"""

import os
import json
from strands import Agent, tool
from strands.models import BedrockModel
from strands_tools import retrieve
from strands_tools import current_time
from strands.tools.mcp import MCPClient
from mcp.client.streamable_http import streamablehttp_client
import requests
from bedrock_agentcore.memory.integrations.strands.config import AgentCoreMemoryConfig, RetrievalConfig
from bedrock_agentcore.memory.integrations.strands.session_manager import AgentCoreMemorySessionManager
from datetime import datetime

# Constants
MODEL_ID = "us.anthropic.claude-sonnet-4-5-20250929-v1:0"
REGION = "us-west-2"
SESSION_ID = "default-session"
ACTOR_ID = "default-actor"

# Model configuration
bedrock_model = BedrockModel(model_id=MODEL_ID, temperature=0.3)

# ============================================================================
# LOAD CONFIGURATIONS FROM JSON FILES
# ============================================================================

# Load Knowledge Base config
try:
    with open('kb_config.json', 'r') as f:
        kb_config = json.load(f)
        kb_id = kb_config.get('knowledge_base_id', 'YOUR_KB_ID_HERE')
except FileNotFoundError:
    kb_id = os.environ.get("KNOWLEDGE_BASE_ID", "YOUR_KB_ID_HERE")

print(f"✓ Knowledge Base ID: {kb_id}")

# Load Memory config
try:
    with open('memory_config.json', 'r') as f:
        memory_config = json.load(f)
        MEMORY_ID = memory_config.get('memory_id')
        print(f"✓ Memory ID: {MEMORY_ID}")
except FileNotFoundError:
    MEMORY_ID = os.environ.get("MEMORY_ID")
    if MEMORY_ID:
        print(f"✓ Memory ID from env: {MEMORY_ID}")

# Load Gateway config
try:
    with open('gateway_config.json', 'r') as f:
        gateway_config = json.load(f)
        GATEWAY_URL = gateway_config.get('gateway_url')
        print(f"✓ Gateway URL: {GATEWAY_URL}")
except FileNotFoundError:
    GATEWAY_URL = os.environ.get("GATEWAY_URL")

# Load Cognito config
try:
    with open('cognito_config.json', 'r') as f:
        cognito_config = json.load(f)
        COGNITO_CLIENT_ID = cognito_config.get('client_id')
        COGNITO_CLIENT_SECRET = cognito_config.get('client_secret')
        COGNITO_DISCOVERY_URL = cognito_config.get('discovery_url')
        RESOURCE_SERVER_ID = cognito_config.get('resource_server_identifier', 'returns-gateway-api')
        print(f"✓ Cognito configured")
except FileNotFoundError:
    COGNITO_CLIENT_ID = os.environ.get("COGNITO_CLIENT_ID")
    COGNITO_CLIENT_SECRET = os.environ.get("COGNITO_CLIENT_SECRET")
    COGNITO_DISCOVERY_URL = os.environ.get("COGNITO_DISCOVERY_URL")
    RESOURCE_SERVER_ID = 'returns-gateway-api'

# ============================================================================
# GATEWAY HELPER FUNCTIONS
# ============================================================================

def get_cognito_token_with_scope(client_id, client_secret, discovery_url, scope):
    """Get Cognito bearer token with a specific OAuth scope"""
    # Extract token endpoint from discovery URL
    discovery_response = requests.get(discovery_url)
    token_endpoint = discovery_response.json()['token_endpoint']
    
    # Get token using client credentials flow
    response = requests.post(
        token_endpoint,
        data={
            'grant_type': 'client_credentials',
            'client_id': client_id,
            'client_secret': client_secret,
            'scope': scope
        },
        headers={'Content-Type': 'application/x-www-form-urlencoded'}
    )
    
    response.raise_for_status()
    return response.json()["access_token"]

def create_mcp_client():
    """Create MCP client for gateway access"""
    if not all([GATEWAY_URL, COGNITO_CLIENT_ID, COGNITO_CLIENT_SECRET, COGNITO_DISCOVERY_URL]):
        print("⚠️  Gateway environment variables not set - gateway tools will not be available")
        return None
    
    try:
        # Build OAuth scopes using resource server identifier
        oauth_scopes = f"{RESOURCE_SERVER_ID}/read {RESOURCE_SERVER_ID}/write {RESOURCE_SERVER_ID}/invoke"
        
        token = get_cognito_token_with_scope(
            COGNITO_CLIENT_ID,
            COGNITO_CLIENT_SECRET,
            COGNITO_DISCOVERY_URL,
            oauth_scopes
        )
        print(f"✓ Gateway configured: {GATEWAY_URL}")
        return MCPClient(
            lambda: streamablehttp_client(
                GATEWAY_URL,
                headers={"Authorization": f"Bearer {token}"},
            )
        )
    except Exception as e:
        print(f"⚠️  Failed to create MCP client: {e}")
        return None

# ============================================================================
# MEMORY CONFIGURATION
# ============================================================================

def create_memory_session_manager(memory_id: str, session_id: str = SESSION_ID, actor_id: str = ACTOR_ID):
    """Create AgentCore Memory session manager"""
    agentcore_memory_config = AgentCoreMemoryConfig(
        memory_id=memory_id,
        session_id=session_id,
        actor_id=actor_id,
        retrieval_config={
        f"app/{actor_id}/semantic": RetrievalConfig(top_k=3),
        f"app/{actor_id}/preferences": RetrievalConfig(top_k=3),
        f"app/{actor_id}/{session_id}/summary": RetrievalConfig(top_k=2),
        }
    )
    
    return AgentCoreMemorySessionManager(
        agentcore_memory_config=agentcore_memory_config,
        region_name=REGION
    )

# System prompt
system_prompt = f"""You are a returns assistant with memory and order lookup capabilities. Remember customer preferences, look up order details, and use the retrieve tool to access Amazon return policy documents for accurate information.

When using the retrieve tool, always pass these parameters:
- knowledgeBaseId: {kb_id}
- region: {REGION}
- text: the search query

You have access to:
- Gateway tools for external operations (like lookup_order)
- Customer conversation history and preferences through memory"""

# Custom tool definitions
@tool

def check_return_eligibility(purchase_date: str, category: str) -> str:
    """Check if an item can be returned based on purchase date and category.
    
    Args:
        purchase_date: Purchase date in YYYY-MM-DD format
        category: Product category (electronics, clothing, books, etc.)
    """
    try:
        purchase = datetime.strptime(purchase_date, '%Y-%m-%d')
        today = datetime.now()
        days_since_purchase = (today - purchase).days
        
        # Return windows by category
        return_windows = {
            'electronics': 30,
            'clothing': 60,
            'books': 30,
            'home': 90,
            'toys': 90,
            'default': 30
        }
        
        window = return_windows.get(category.lower(), return_windows['default'])
        
        if days_since_purchase <= window:
            return f"✓ Eligible for return. Item purchased {days_since_purchase} days ago. {category.title()} have a {window}-day return window. You have {window - days_since_purchase} days remaining."
        else:
            return f"✗ Not eligible for return. Item purchased {days_since_purchase} days ago, which exceeds the {window}-day return window for {category}."
    except ValueError:
        return "Error: Invalid date format. Please use YYYY-MM-DD format."

@tool
def calculate_refund_amount(price: float, condition: str, return_reason: str) -> str:
    """Calculate refund amount based on item price, condition, and return reason.
    
    Args:
        price: Original purchase price
        condition: Item condition (new, like-new, used, damaged)
        return_reason: Reason for return (defect, wrong-item, changed-mind, damaged-shipping)
    """
    refund_percentage = 1.0
    
    # Adjust based on condition
    condition_adjustments = {
        'new': 1.0,
        'like-new': 1.0,
        'used': 0.8,
        'damaged': 0.5
    }
    
    # Adjust based on reason
    reason_adjustments = {
        'defect': 1.0,
        'wrong-item': 1.0,
        'damaged-shipping': 1.0,
        'changed-mind': 0.9  # 10% restocking fee
    }
    
    condition_factor = condition_adjustments.get(condition.lower(), 0.8)
    reason_factor = reason_adjustments.get(return_reason.lower(), 0.9)
    
    refund_amount = price * condition_factor * reason_factor
    
    details = []
    if condition_factor < 1.0:
        details.append(f"Condition adjustment: {condition_factor * 100}%")
    if reason_factor < 1.0:
        details.append(f"Restocking fee: {(1 - reason_factor) * 100}%")
    
    result = f"Refund amount: ${refund_amount:.2f} (Original: ${price:.2f})"
    if details:
        result += "\n" + "\n".join(details)
    
    return result

@tool
def format_policy_response(policy_text: str, customer_situation: str = '') -> str:
    """Format policy information in a customer-friendly, easy-to-read way.
    
    Args:
        policy_text: The policy text to format
        customer_situation: Optional context about the customer's specific situation
    """
    formatted = "📋 Return Policy Summary\n" + "=" * 40 + "\n\n"
    
    if customer_situation:
        formatted += f"For your situation: {customer_situation}\n\n"
    
    # Clean up and format the policy text
    lines = policy_text.strip().split('\n')
    for line in lines:
        line = line.strip()
        if line:
            if line.isupper() or line.endswith(':'):
                formatted += f"\n{line}\n"
            else:
                formatted += f"• {line}\n"
    
    formatted += "\n" + "=" * 40
    formatted += "\n\n💡 Tip: If you have questions, I'm here to help clarify any part of this policy!"
    
    return formatted


def run_agent(user_input: str, session_id: str = SESSION_ID, actor_id: str = ACTOR_ID):
    """Run the agent with user input"""
    
    # Build tools list
    custom_tools = [retrieve, current_time, check_return_eligibility, calculate_refund_amount, format_policy_response]
    
    # Configure memory
    memory_id = MEMORY_ID
    if not memory_id:
        print("⚠️  MEMORY_ID not set - agent will run without memory")
        session_manager = None
    else:
        session_manager = create_memory_session_manager(memory_id, session_id, actor_id)
        print(f"✓ Memory session configured for actor: {actor_id}, session: {session_id}")
    
    # Try to add gateway tools
    mcp_client = create_mcp_client()
    
    if mcp_client:
        try:
            # Keep MCP client active during agent execution
            with mcp_client:
                # Get gateway tools from MCP client
                gateway_tools = list(mcp_client.list_tools_sync())
                print(f"✓ Loaded {len(gateway_tools)} gateway tools")
                
                # Create agent with gateway tools
                agent = Agent(
                    model=bedrock_model,
                    tools=custom_tools + gateway_tools,
                    system_prompt=system_prompt,
                    session_manager=session_manager
                )
                
                response = agent(user_input)
                return response.message["content"][0]["text"]
        except Exception as e:
            print(f"⚠️  Failed to use gateway tools: {e}")
            # Fall back to agent without gateway tools
    
    # Create agent without gateway tools (fallback or no gateway)
    agent = Agent(
        model=bedrock_model,
        tools=custom_tools,
        system_prompt=system_prompt,
        session_manager=session_manager
    )
    
    response = agent(user_input)
    return response.message["content"][0]["text"]

if __name__ == "__main__":
    # Example usage
    user_query = "Hello, how can you help me?"
    result = run_agent(user_query)
    print("\n" + "="*80)
    print("AGENT RESPONSE:")
    print("="*80)
    print(result)
