"""
AgentCore Runtime Agent: returns_agent_runtime
Generated by AgentCore MCP Server

This agent is ready to deploy to AgentCore Runtime with:
1. BedrockAgentCoreApp entrypoint
2. Memory integration (optional)
3. Gateway tools (optional)
4. Knowledge Base access (optional)
"""

import os
import json
from bedrock_agentcore.runtime import BedrockAgentCoreApp
from strands import Agent, tool
from strands.models import BedrockModel
from strands_tools import retrieve
from strands_tools import current_time
from strands.tools.mcp import MCPClient
from mcp.client.streamable_http import streamablehttp_client
import requests
from bedrock_agentcore.memory.integrations.strands.config import AgentCoreMemoryConfig, RetrievalConfig
from bedrock_agentcore.memory.integrations.strands.session_manager import AgentCoreMemorySessionManager
from datetime import datetime

# Constants
MODEL_ID = "us.anthropic.claude-sonnet-4-5-20250929-v1:0"
REGION = "us-west-2"
SESSION_ID = "default-session"
ACTOR_ID = "default-actor"

# Initialize app only (don't initialize model at module level)
app = BedrockAgentCoreApp()

# Environment variables - loaded at runtime, not at module import
# These will be accessed inside the invoke function
kb_id = os.environ.get("KNOWLEDGE_BASE_ID", "YOUR_KB_ID_HERE")
print(f"✓ Knowledge Base ID: {kb_id}")

# ============================================================================
# CUSTOM TOOLS
# ============================================================================

@tool
def check_return_eligibility(purchase_date: str, category: str) -> str:
    """Check if an item can be returned based on purchase date and category.
    
    Args:
        purchase_date: Purchase date in YYYY-MM-DD format
        category: Product category (electronics, clothing, books, etc.)
    """
    try:
        purchase = datetime.strptime(purchase_date, '%Y-%m-%d')
        today = datetime.now()
        days_since_purchase = (today - purchase).days
        
        # Return windows by category
        return_windows = {
            'electronics': 30,
            'clothing': 60,
            'books': 30,
            'home': 90,
            'toys': 90,
            'default': 30
        }
        
        window = return_windows.get(category.lower(), return_windows['default'])
        
        if days_since_purchase <= window:
            return f"✓ Eligible for return. Item purchased {days_since_purchase} days ago. {category.title()} have a {window}-day return window. You have {window - days_since_purchase} days remaining."
        else:
            return f"✗ Not eligible for return. Item purchased {days_since_purchase} days ago, which exceeds the {window}-day return window for {category}."
    except ValueError:
        return "Error: Invalid date format. Please use YYYY-MM-DD format."

@tool
def calculate_refund_amount(price: float, condition: str, return_reason: str) -> str:
    """Calculate refund amount based on item price, condition, and return reason.
    
    Args:
        price: Original purchase price
        condition: Item condition (new, like-new, used, damaged)
        return_reason: Reason for return (defect, wrong-item, changed-mind, damaged-shipping)
    """
    refund_percentage = 1.0
    
    # Adjust based on condition
    condition_adjustments = {
        'new': 1.0,
        'like-new': 1.0,
        'used': 0.8,
        'damaged': 0.5
    }
    
    # Adjust based on reason
    reason_adjustments = {
        'defect': 1.0,
        'wrong-item': 1.0,
        'damaged-shipping': 1.0,
        'changed-mind': 0.9  # 10% restocking fee
    }
    
    condition_factor = condition_adjustments.get(condition.lower(), 0.8)
    reason_factor = reason_adjustments.get(return_reason.lower(), 0.9)
    
    refund_amount = price * condition_factor * reason_factor
    
    details = []
    if condition_factor < 1.0:
        details.append(f"Condition adjustment: {condition_factor * 100}%")
    if reason_factor < 1.0:
        details.append(f"Restocking fee: {(1 - reason_factor) * 100}%")
    
    result = f"Refund amount: ${refund_amount:.2f} (Original: ${price:.2f})"
    if details:
        result += "\n" + "\n".join(details)
    
    return result

@tool
def format_policy_response(policy_text: str, customer_situation: str = '') -> str:
    """Format policy information in a customer-friendly, easy-to-read way.
    
    Args:
        policy_text: The policy text to format
        customer_situation: Optional context about the customer's specific situation
    """
    formatted = "📋 Return Policy Summary\n" + "=" * 40 + "\n\n"
    
    if customer_situation:
        formatted += f"For your situation: {customer_situation}\n\n"
    
    # Clean up and format the policy text
    lines = policy_text.strip().split('\n')
    for line in lines:
        line = line.strip()
        if line:
            if line.isupper() or line.endswith(':'):
                formatted += f"\n{line}\n"
            else:
                formatted += f"• {line}\n"
    
    formatted += "\n" + "=" * 40
    formatted += "\n\n💡 Tip: If you have questions, I'm here to help clarify any part of this policy!"
    
    return formatted

# ============================================================================
# GATEWAY HELPER FUNCTIONS
# ============================================================================

def get_cognito_token_with_scope(client_id, client_secret, discovery_url, scope):
    """Get Cognito bearer token with a specific OAuth scope"""
    # Extract token endpoint from discovery URL
    discovery_response = requests.get(discovery_url)
    token_endpoint = discovery_response.json()['token_endpoint']
    
    # Get token using client credentials flow
    response = requests.post(
        token_endpoint,
        data={
            'grant_type': 'client_credentials',
            'client_id': client_id,
            'client_secret': client_secret,
            'scope': scope
        },
        headers={'Content-Type': 'application/x-www-form-urlencoded'}
    )
    
    response.raise_for_status()
    return response.json()["access_token"]

def create_mcp_client():
    """Create MCP client for gateway access"""
    # Get environment variables
    gateway_url = os.environ.get("GATEWAY_URL")
    cognito_client_id = os.environ.get("COGNITO_CLIENT_ID")
    cognito_client_secret = os.environ.get("COGNITO_CLIENT_SECRET")
    cognito_discovery_url = os.environ.get("COGNITO_DISCOVERY_URL")
    oauth_scopes = os.environ.get("OAUTH_SCOPES", "returns-gateway-api/read returns-gateway-api/write returns-gateway-api/invoke")
    
    if not all([gateway_url, cognito_client_id, cognito_client_secret, cognito_discovery_url]):
        return None
    
    try:
        token = get_cognito_token_with_scope(
            cognito_client_id,
            cognito_client_secret,
            cognito_discovery_url,
            oauth_scopes
        )
        return MCPClient(
            lambda: streamablehttp_client(
                gateway_url,
                headers={"Authorization": f"Bearer {token}"},
            )
        )
    except Exception as e:
        print(f"Warning: Failed to create MCP client: {e}")
        return None

system_prompt = f"""Production returns assistant with full memory and gateway capabilities. Use the retrieve tool to access Amazon return policy documents for accurate information.

When using the retrieve tool, always pass these parameters:
- knowledgeBaseId: {kb_id}
- region: {REGION}
- text: the search query

You have access to:
- Gateway tools for external operations (like lookup_order)
- Customer conversation history and preferences through memory
- Custom tools for checking eligibility, calculating refunds, and formatting policies"""

@app.entrypoint
def invoke(payload, context=None):
    """AgentCore Runtime entrypoint"""
    try:
        # Initialize model inside the function (not at module level)
        bedrock_model = BedrockModel(model_id=MODEL_ID, temperature=0.3)
        
        # Get environment variables
        memory_id = os.environ.get("MEMORY_ID")
        if not memory_id:
            return "Error: MEMORY_ID environment variable is required"
        
        session_id = context.session_id if context else SESSION_ID
        actor_id = payload.get("actor_id", ACTOR_ID)
        
        # Configure memory with retrieval settings
        agentcore_memory_config = AgentCoreMemoryConfig(
            memory_id=memory_id,
            session_id=session_id,
            actor_id=actor_id,
            retrieval_config={
            f"app/{actor_id}/semantic": RetrievalConfig(top_k=3),
            f"app/{actor_id}/preferences": RetrievalConfig(top_k=3),
            f"app/{actor_id}/{session_id}/summary": RetrievalConfig(top_k=2),
            }
        )
        
        session_manager = AgentCoreMemorySessionManager(
            agentcore_memory_config=agentcore_memory_config,
            region_name=REGION
        )
        
        # Custom tools list - ALL original tools plus retrieve and current_time
        custom_tools = [retrieve, current_time, check_return_eligibility, calculate_refund_amount, format_policy_response]
        
        # Try to create MCP client for gateway tools
        mcp_client = create_mcp_client()
        
        if mcp_client:
            try:
                # Keep MCP client active during agent execution
                with mcp_client:
                    # Get gateway tools from MCP client
                    gateway_tools = list(mcp_client.list_tools_sync())
                    
                    # Create agent with all tools
                    agent = Agent(
                        model=bedrock_model,
                        tools=custom_tools + gateway_tools,
                        system_prompt=system_prompt,
                        session_manager=session_manager
                    )
                    
                    user_input = payload.get("prompt", "")
                    response = agent(user_input)
                    return response.message["content"][0]["text"]
            except Exception as e:
                print(f"Warning: Failed to use gateway tools: {e}")
                # Fall back to agent without gateway tools
        
        # Create agent without gateway tools (fallback)
        agent = Agent(
            model=bedrock_model,
            tools=custom_tools,
            system_prompt=system_prompt,
            session_manager=session_manager
        )
        
        user_input = payload.get("prompt", "")
        response = agent(user_input)
        return response.message["content"][0]["text"]
    
    except Exception as e:
        error_msg = f"Agent invocation failed: {str(e)}"
        print(error_msg)
        import traceback
        traceback.print_exc()
        return error_msg

if __name__ == "__main__":
    app.run()
