"""
AgentCore Strands Agent Generation Handlers

Implementation of handlers for generating Strands agent code with various
configurations and integrations.
"""

from typing import Dict


async def handle_generate_strands_agent(args: Dict) -> Dict:
    """Generate standalone Strands Agent Python code"""
    
    agent_name = args["agent_name"]
    system_prompt = args["system_prompt"]
    model_id = args.get("model_id", "us.anthropic.claude-sonnet-4-5-20250929-v1:0")
    temperature = args.get("temperature", 0.3)
    region = args.get("region", "us-west-2")
    tools = args.get("tools", [])
    custom_tools = args.get("custom_tools", [])
    
    # Integration flags
    include_memory = args.get("include_memory", False)
    memory_namespaces = args.get("memory_namespaces", ["semantic", "preferences", "summary"])
    include_kb = args.get("include_kb", False)
    include_gateway = args.get("include_gateway", False)
    
    # Build imports
    imports = ["import os", "from strands import Agent, tool"]
    imports.append("from strands.models import BedrockModel")
    
    if "retrieve" in tools or include_kb:
        imports.append("from strands_tools import retrieve")
    if "current_time" in tools:
        imports.append("from strands_tools import current_time")
    
    if include_gateway:
        imports.append("from strands.tools.mcp import MCPClient")
        imports.append("from mcp.client.streamable_http import streamablehttp_client")
        imports.append("import requests")
    
    if include_memory:
        imports.append("from bedrock_agentcore.memory.integrations.strands.config import AgentCoreMemoryConfig, RetrievalConfig")
        imports.append("from bedrock_agentcore.memory.integrations.strands.session_manager import AgentCoreMemorySessionManager")
    
    if custom_tools:
        imports.append("from datetime import datetime")
    
    # Build tool list
    tool_list = []
    if "retrieve" in tools or include_kb:
        tool_list.append("retrieve")
    if "current_time" in tools:
        tool_list.append("current_time")
    
    # Generate code
    code = f'''"""
Standalone Strands Agent: {agent_name}
Generated by AgentCore MCP Server

Integrations:
- Memory: {"Enabled" if include_memory else "Disabled"}
- Gateway: {"Enabled" if include_gateway else "Disabled"}
- Knowledge Base: {"Enabled" if include_kb else "Disabled"}
"""

{chr(10).join(imports)}

# Constants
MODEL_ID = "{model_id}"
REGION = "{region}"
SESSION_ID = "default-session"
ACTOR_ID = "default-actor"

# Model configuration
bedrock_model = BedrockModel(model_id=MODEL_ID, temperature={temperature})
'''
    
    # Add Knowledge Base configuration
    if include_kb:
        code += '''
# ============================================================================
# KNOWLEDGE BASE CONFIGURATION
# ============================================================================

kb_id = os.environ.get("KNOWLEDGE_BASE_ID", "YOUR_KB_ID_HERE")
print(f"✓ Knowledge Base ID: {kb_id}")
'''
    
    # Add Gateway helper functions
    if include_gateway:
        code += '''
# ============================================================================
# GATEWAY HELPER FUNCTIONS
# ============================================================================

def get_cognito_token_with_scope(client_id, client_secret, discovery_url, scope):
    """Get Cognito bearer token with a specific OAuth scope"""
    # Extract token endpoint from discovery URL
    discovery_response = requests.get(discovery_url)
    token_endpoint = discovery_response.json()['token_endpoint']
    
    # Get token using client credentials flow
    response = requests.post(
        token_endpoint,
        data={{
            'grant_type': 'client_credentials',
            'client_id': client_id,
            'client_secret': client_secret,
            'scope': scope
        }},
        headers={{'Content-Type': 'application/x-www-form-urlencoded'}}
    )
    
    response.raise_for_status()
    return response.json()["access_token"]

def create_mcp_client():
    """Create MCP client for gateway access"""
    # Get environment variables
    gateway_url = os.environ.get("GATEWAY_URL")
    cognito_client_id = os.environ.get("COGNITO_CLIENT_ID")
    cognito_client_secret = os.environ.get("COGNITO_CLIENT_SECRET")
    cognito_discovery_url = os.environ.get("COGNITO_DISCOVERY_URL")
    oauth_scopes = os.environ.get("OAUTH_SCOPES", "returns-gateway/read returns-gateway/write returns-gateway/invoke")
    
    if not all([gateway_url, cognito_client_id, cognito_client_secret, cognito_discovery_url]):
        print("⚠️  Gateway environment variables not set - gateway tools will not be available")
        return None
    
    try:
        token = get_cognito_token_with_scope(
            cognito_client_id,
            cognito_client_secret,
            cognito_discovery_url,
            oauth_scopes
        )
        print(f"✓ Gateway configured: {gateway_url}")
        return MCPClient(
            lambda: streamablehttp_client(
                gateway_url,
                headers={{"Authorization": f"Bearer {{token}}"}},
            )
        )
    except Exception as e:
        print(f"⚠️  Failed to create MCP client: {{e}}")
        return None
'''
    
    # Add Memory configuration
    if include_memory:
        # Build memory retrieval config
        retrieval_configs = []
        for ns in memory_namespaces:
            if ns == "summary":
                retrieval_configs.append(f'        f"app/{{actor_id}}/{{session_id}}/summary": RetrievalConfig(top_k=2),')
            else:
                retrieval_configs.append(f'        f"app/{{actor_id}}/{ns}": RetrievalConfig(top_k=3),')
        
        code += f'''
# ============================================================================
# MEMORY CONFIGURATION
# ============================================================================

def create_memory_session_manager(memory_id: str, session_id: str = SESSION_ID, actor_id: str = ACTOR_ID):
    """Create AgentCore Memory session manager"""
    agentcore_memory_config = AgentCoreMemoryConfig(
        memory_id=memory_id,
        session_id=session_id,
        actor_id=actor_id,
        retrieval_config={{
{chr(10).join(retrieval_configs)}
        }}
    )
    
    return AgentCoreMemorySessionManager(
        agentcore_memory_config=agentcore_memory_config,
        region_name=REGION
    )
'''
    
    # Add system prompt
    kb_note = f'\\n\\nWhen using the retrieve tool, always pass these parameters:\\n- knowledgeBaseId: {{kb_id}}\\n- region: {{REGION}}\\n- text: the search query' if include_kb else ""
    gateway_note = "\\n- Gateway tools for external operations" if include_gateway else ""
    memory_note = "\\n- Customer conversation history and preferences through memory" if include_memory else ""
    
    code += f'''
# System prompt
system_prompt = f"""{system_prompt}{kb_note}{gateway_note}{memory_note}"""
'''
    
    # Add custom tool definitions
    if custom_tools:
        code += "\n# Custom tool definitions\n"
        for tool_def in custom_tools:
            tool_name = tool_def.get("name", "custom_tool")
            tool_desc = tool_def.get("description", "Custom tool")
            tool_code = tool_def.get("code", 'return "Not implemented"')
            
            # Extract any import statements from the tool code
            tool_lines = tool_code.strip().split('\n')
            tool_imports = []
            tool_body_lines = []
            
            for line in tool_lines:
                stripped = line.strip()
                if stripped.startswith('from ') or stripped.startswith('import '):
                    # Skip imports - they should already be at the top
                    continue
                else:
                    tool_body_lines.append(line)
            
            # Reconstruct tool code without imports
            clean_tool_code = '\n'.join(tool_body_lines)
            
            # Automatically add @tool decorator if not present
            if not clean_tool_code.strip().startswith("@tool"):
                code += f'''@tool
{clean_tool_code}

'''
            else:
                code += f'''{clean_tool_code}

'''
            tool_list.append(tool_name)
    
    # Build the run_agent function with integrations
    code += f'''
def run_agent(user_input: str, session_id: str = SESSION_ID, actor_id: str = ACTOR_ID):
    """Run the agent with user input"""
    
    # Build tools list
    custom_tools = [{", ".join(tool_list)}]
    
'''
    
    # Configure memory FIRST (before gateway logic)
    if include_memory:
        code += '''    # Configure memory
    memory_id = os.environ.get("MEMORY_ID")
    if not memory_id:
        print("⚠️  MEMORY_ID not set - agent will run without memory")
        session_manager = None
    else:
        session_manager = create_memory_session_manager(memory_id, session_id, actor_id)
        print(f"✓ Memory configured: {memory_id}")
    
'''
    
    # Handle gateway integration
    if include_gateway:
        code += '''    # Try to add gateway tools
    mcp_client = create_mcp_client()
    
    if mcp_client:
        try:
            # Keep MCP client active during agent execution
            with mcp_client:
                # Get gateway tools from MCP client
                gateway_tools = list(mcp_client.list_tools_sync())
                print(f"✓ Loaded {len(gateway_tools)} gateway tools")
                
                # Create agent with gateway tools
                agent = Agent(
                    model=bedrock_model,
                    tools=custom_tools + gateway_tools,
                    system_prompt=system_prompt'''
        
        if include_memory:
            code += ''',
                    session_manager=session_manager'''
        
        code += '''
                )
                
                response = agent(user_input)
                return response.message["content"][0]["text"]
        except Exception as e:
            print(f"⚠️  Failed to use gateway tools: {e}")
            # Fall back to agent without gateway tools
    
    # Create agent without gateway tools (fallback or no gateway)
    agent = Agent(
        model=bedrock_model,
        tools=custom_tools,
        system_prompt=system_prompt'''
        
        if include_memory:
            code += ''',
        session_manager=session_manager'''
        
        code += '''
    )
    
    response = agent(user_input)
    return response.message["content"][0]["text"]
'''
    else:
        # No gateway - simple agent creation
        code += '''    # Create agent
    agent = Agent(
        model=bedrock_model,
        tools=custom_tools,
        system_prompt=system_prompt'''
        
        if include_memory:
            code += ''',
        session_manager=session_manager'''
        
        code += '''
    )
    
    response = agent(user_input)
    return response.message["content"][0]["text"]
'''
    
    code += '''
if __name__ == "__main__":
    # Example usage
    user_query = "Hello, how can you help me?"
    result = run_agent(user_query)
    print("\\n" + "="*80)
    print("AGENT RESPONSE:")
    print("="*80)
    print(result)
'''
    
    # Generate instructions
    env_vars = []
    if include_memory:
        env_vars.append("MEMORY_ID")
    if include_kb:
        env_vars.append("KNOWLEDGE_BASE_ID")
    if include_gateway:
        env_vars.extend(["GATEWAY_URL", "COGNITO_CLIENT_ID", "COGNITO_CLIENT_SECRET", "COGNITO_DISCOVERY_URL"])
    
    instructions = f"Save this code to {agent_name}.py"
    if env_vars:
        instructions += f"\nSet environment variables: {', '.join(env_vars)}"
    instructions += f"\nRun with: python {agent_name}.py"
    
    return {
        "status": "generated",
        "agent_name": agent_name,
        "filename": f"{agent_name}.py",
        "code": code,
        "instructions": instructions,
        "integrations": {
            "memory": include_memory,
            "gateway": include_gateway,
            "knowledge_base": include_kb
        },
        "required_env_vars": env_vars
    }


async def handle_generate_agentcore_runtime_agent(args: Dict) -> Dict:
    """Generate AgentCore Runtime-ready Strands Agent with BedrockAgentCoreApp entrypoint"""
    
    agent_name = args["agent_name"]
    system_prompt = args["system_prompt"]
    model_id = args.get("model_id", "us.anthropic.claude-sonnet-4-5-20250929-v1:0")
    temperature = args.get("temperature", 0.3)
    include_memory = args.get("include_memory", True)
    memory_namespaces = args.get("memory_namespaces", ["semantic", "preferences", "summary"])
    include_kb = args.get("include_kb", False)
    include_gateway = args.get("include_gateway", False)
    additional_tools = args.get("additional_tools", [])
    region = args.get("region")
    if not region:
        raise ValueError("region parameter is required")
    
    # Build imports
    imports = [
        "import os",
        "import json",
        "from bedrock_agentcore.runtime import BedrockAgentCoreApp",
        "from strands import Agent, tool",
        "from strands.models import BedrockModel"
    ]
    
    tool_list = []
    
    if include_kb:
        imports.append("from strands_tools import retrieve")
        tool_list.append("retrieve")
    
    if "current_time" in additional_tools:
        imports.append("from strands_tools import current_time")
        tool_list.append("current_time")
    
    if include_gateway:
        imports.append("from strands.tools.mcp import MCPClient")
        imports.append("from mcp.client.streamable_http import streamablehttp_client")
        imports.append("import requests")
    
    if include_memory:
        imports.append("from bedrock_agentcore.memory.integrations.strands.config import AgentCoreMemoryConfig, RetrievalConfig")
        imports.append("from bedrock_agentcore.memory.integrations.strands.session_manager import AgentCoreMemorySessionManager")
    
    # Generate code
    code = f'''"""
AgentCore Runtime Agent: {agent_name}
Generated by AgentCore MCP Server

This agent is ready to deploy to AgentCore Runtime with:
1. BedrockAgentCoreApp entrypoint
2. Memory integration (optional)
3. Gateway tools (optional)
4. Knowledge Base access (optional)
"""

{chr(10).join(imports)}

# Constants
MODEL_ID = "{model_id}"
REGION = "{region}"
SESSION_ID = "default-session"
ACTOR_ID = "default-actor"

# Initialize app only (don't initialize model at module level)
app = BedrockAgentCoreApp()

# Environment variables - loaded at runtime, not at module import
# These will be accessed inside the invoke function
'''
    
    if include_kb:
        code += '''kb_id = os.environ.get("KNOWLEDGE_BASE_ID", "YOUR_KB_ID_HERE")
print(f"✓ Knowledge Base ID: {kb_id}")
'''
    
    # Remove module-level environment variable loading
    # Memory ID will be loaded inside invoke function
    
    if include_gateway:
        code += '''
# ============================================================================
# GATEWAY HELPER FUNCTIONS
# ============================================================================

def get_cognito_token_with_scope(client_id, client_secret, discovery_url, scope):
    """Get Cognito bearer token with a specific OAuth scope"""
    # Extract token endpoint from discovery URL
    discovery_response = requests.get(discovery_url)
    token_endpoint = discovery_response.json()['token_endpoint']
    
    # Get token using client credentials flow
    response = requests.post(
        token_endpoint,
        data={{
            'grant_type': 'client_credentials',
            'client_id': client_id,
            'client_secret': client_secret,
            'scope': scope
        }},
        headers={{'Content-Type': 'application/x-www-form-urlencoded'}}
    )
    
    response.raise_for_status()
    return response.json()["access_token"]

def create_mcp_client():
    """Create MCP client for gateway access"""
    # Get environment variables
    gateway_url = os.environ.get("GATEWAY_URL")
    cognito_client_id = os.environ.get("COGNITO_CLIENT_ID")
    cognito_client_secret = os.environ.get("COGNITO_CLIENT_SECRET")
    cognito_discovery_url = os.environ.get("COGNITO_DISCOVERY_URL")
    oauth_scopes = os.environ.get("OAUTH_SCOPES", "returns-gateway/read returns-gateway/write returns-gateway/invoke")
    
    if not all([gateway_url, cognito_client_id, cognito_client_secret, cognito_discovery_url]):
        return None
    
    try:
        token = get_cognito_token_with_scope(
            cognito_client_id,
            cognito_client_secret,
            cognito_discovery_url,
            oauth_scopes
        )
        return MCPClient(
            lambda: streamablehttp_client(
                gateway_url,
                headers={{"Authorization": f"Bearer {{token}}"}},
            )
        )
    except Exception as e:
        print(f"Warning: Failed to create MCP client: {{e}}")
        return None
'''
    
    # System prompt
    kb_note = f'\\n\\nWhen using the retrieve tool, always pass these parameters:\\n- knowledgeBaseId: {{kb_id}}\\n- region: {{REGION}}\\n- text: the search query' if include_kb else ""
    gateway_note = "\\n- Gateway tools for external operations" if include_gateway else ""
    memory_note = "\\n- Customer conversation history and preferences through memory" if include_memory else ""
    
    code += f'''
system_prompt = f"""{system_prompt}{kb_note}{gateway_note}{memory_note}"""

@app.entrypoint
def invoke(payload, context=None):
    """AgentCore Runtime entrypoint"""
    try:
        # Initialize model inside the function (not at module level)
        bedrock_model = BedrockModel(model_id=MODEL_ID, temperature={temperature})
        
        # Get environment variables
'''
    
    if include_memory:
        # Build memory retrieval config
        retrieval_configs = []
        for ns in memory_namespaces:
            if ns == "summary":
                retrieval_configs.append(f'            f"app/{{actor_id}}/{{session_id}}/summary": RetrievalConfig(top_k=2),')
            else:
                retrieval_configs.append(f'            f"app/{{actor_id}}/{ns}": RetrievalConfig(top_k=3),')
        
        code += f'''        memory_id = os.environ.get("MEMORY_ID")
        if not memory_id:
            return "Error: MEMORY_ID environment variable is required"
        
        session_id = context.session_id if context else SESSION_ID
        actor_id = payload.get("actor_id", ACTOR_ID)
        
        # Configure memory with retrieval settings
        agentcore_memory_config = AgentCoreMemoryConfig(
            memory_id=memory_id,
            session_id=session_id,
            actor_id=actor_id,
            retrieval_config={{
{chr(10).join(retrieval_configs)}
            }}
        )
        
        session_manager = AgentCoreMemorySessionManager(
            agentcore_memory_config=agentcore_memory_config,
            region_name=REGION
        )
        
        # Custom tools list
        custom_tools = [{", ".join(tool_list)}]
        
'''
    else:
        code += '''        session_id = context.session_id if context else SESSION_ID
        actor_id = payload.get("actor_id", ACTOR_ID)
        
        # Custom tools list
        custom_tools = [''' + ", ".join(tool_list) + ''']
        
'''
    
    if include_gateway:
        code += '''        # Try to create MCP client for gateway tools
        mcp_client = create_mcp_client()
        
        if mcp_client:
            try:
                # Keep MCP client active during agent execution
                with mcp_client:
                    # Get gateway tools from MCP client
                    gateway_tools = list(mcp_client.list_tools_sync())
                    
                    # Create agent with all tools
                    agent = Agent(
                        model=bedrock_model,
                        tools=custom_tools + gateway_tools,
                        system_prompt=system_prompt'''
        
        if include_memory:
            code += ''',
                        session_manager=session_manager'''
        
        code += '''
                    )
                    
                    user_input = payload.get("prompt", "")
                    response = agent(user_input)
                    return response.message["content"][0]["text"]
            except Exception as e:
                print(f"Warning: Failed to use gateway tools: {{e}}")
                # Fall back to agent without gateway tools
        
        # Create agent without gateway tools (fallback)
        agent = Agent(
            model=bedrock_model,
            tools=custom_tools,
            system_prompt=system_prompt'''
        
        if include_memory:
            code += ''',
            session_manager=session_manager'''
        
        code += '''
        )
        
        user_input = payload.get("prompt", "")
        response = agent(user_input)
        return response.message["content"][0]["text"]
'''
    else:
        code += '''        # Create agent
        agent = Agent(
            model=bedrock_model,
            tools=custom_tools,
            system_prompt=system_prompt'''
        
        if include_memory:
            code += ''',
            session_manager=session_manager'''
        
        code += '''
        )
        
        user_input = payload.get("prompt", "")
        response = agent(user_input)
        return response.message["content"][0]["text"]
'''
    
    code += '''    
    except Exception as e:
        error_msg = f"Agent invocation failed: {{str(e)}}"
        print(error_msg)
        import traceback
        traceback.print_exc()
        return error_msg

if __name__ == "__main__":
    app.run()
'''
    
    # Generate deployment instructions
    env_vars = []
    if include_memory:
        env_vars.append("MEMORY_ID")
    if include_kb:
        env_vars.append("KNOWLEDGE_BASE_ID")
    if include_gateway:
        env_vars.extend(["GATEWAY_URL", "COGNITO_CLIENT_ID", "COGNITO_CLIENT_SECRET", "COGNITO_DISCOVERY_URL"])
    
    instructions = f"""1. Save this code to {agent_name}.py
2. Configure Runtime deployment:
   - Use MCP tool: agentcore_runtime_configure
   - Set entrypoint: {agent_name}.py
   - Set agent_name: {agent_name}
3. Launch to Runtime:
   - Use MCP tool: agentcore_runtime_launch
   - Set environment variables: {", ".join(env_vars)}
4. Test deployment:
   - Use MCP tool: agentcore_runtime_status
   - Use MCP tool: agentcore_runtime_invoke"""
    
    return {
        "status": "generated",
        "agent_name": agent_name,
        "filename": f"{agent_name}.py",
        "code": code,
        "instructions": instructions.strip(),
        "required_env_vars": env_vars
    }


# ============================================================================
# MAIN
